version: '3'
services:
  payment_router:
    image: node:10-alpine
    working_dir: /usr/local/app
    command: npm run start:dev
    restart: on-failure
    environment:
      PORT: ${PORT}
      PUBLIC_KEY: ${PUBLIC_KEY}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    ports:
      - '8002:8000'
    volumes:
      - .:/usr/local/app
    networks:
      - payment_router

networks:
  payment_router:
    external:
      name: payment_router
